### ISSUE TITLE
Autoflow cannot run under meteor 1.2

### ISSUE THREAD

**Issue by ericdai** [fullflavedave/meteor-autoflow#1]
I install meteor1.2 and run meteor-autoflow demo，and it report as below：
=> Started proxy.                             
=> Started MongoDB.                           
W20150930-20:48:14.482(8)? (STDERR)           
W20150930-20:48:14.483(8)? (STDERR) /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/boot.js:283
W20150930-20:48:14.483(8)? (STDERR) }).run(); 
W20150930-20:48:14.483(8)? (STDERR)    ^      
W20150930-20:48:14.600(8)? (STDERR) TypeError: Object #<Object> has no method 'methods'
W20150930-20:48:14.601(8)? (STDERR)     at Package (packages/fullflavedave_autoflow/packages/fullflavedave_autoflow.js:64:1)
W20150930-20:48:14.601(8)? (STDERR)     at Package (packages/fullflavedave_autoflow/packages/fullflavedave_autoflow.js:88:1)
W20150930-20:48:14.601(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/packages/fullflavedave_autoflow.js:116:4
W20150930-20:48:14.601(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/packages/fullflavedave_autoflow.js:125:3
W20150930-20:48:14.601(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/boot.js:242:10
W20150930-20:48:14.601(8)? (STDERR)     at Array.forEach (native)
W20150930-20:48:14.601(8)? (STDERR)     at Function._.each._.forEach (/Users/dycbaba/.meteor/packages/meteor-tool/.1.1.9.oddn07++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150930-20:48:14.601(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8                        
W20150930-20:48:51.579(8)? (STDERR)           
W20150930-20:48:51.580(8)? (STDERR) /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/boot.js:283
W20150930-20:48:51.580(8)? (STDERR) }).run();
W20150930-20:48:51.580(8)? (STDERR)    ^
W20150930-20:48:51.585(8)? (STDERR) TypeError: Object #<Object> has no method 'methods'
W20150930-20:48:51.585(8)? (STDERR)     at Package (packages/fullflavedave_autoflow/packages/fullflavedave_autoflow.js:64:1)
W20150930-20:48:51.585(8)? (STDERR)     at Package (packages/fullflavedave_autoflow/packages/fullflavedave_autoflow.js:88:1)
W20150930-20:48:51.585(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/packages/fullflavedave_autoflow.js:116:4
W20150930-20:48:51.585(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/packages/fullflavedave_autoflow.js:125:3
W20150930-20:48:51.586(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/boot.js:242:10
W20150930-20:48:51.586(8)? (STDERR)     at Array.forEach (native)
W20150930-20:48:51.586(8)? (STDERR)     at Function._.each._.forEach (/Users/dycbaba/.meteor/packages/meteor-tool/.1.1.9.oddn07++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150930-20:48:51.586(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
W20150930-20:48:55.161(8)? (STDERR)           
W20150930-20:48:55.161(8)? (STDERR) /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/boot.js:283
W20150930-20:48:55.161(8)? (STDERR) }).run();
W20150930-20:48:55.161(8)? (STDERR)    ^
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20150930-20:48:55.242(8)? (STDERR) TypeError: Object #<Object> has no method 'methods'
W20150930-20:48:55.242(8)? (STDERR)     at Package (packages/fullflavedave_autoflow/packages/fullflavedave_autoflow.js:64:1)
W20150930-20:48:55.242(8)? (STDERR)     at Package (packages/fullflavedave_autoflow/packages/fullflavedave_autoflow.js:88:1)
W20150930-20:48:55.242(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/packages/fullflavedave_autoflow.js:116:4
W20150930-20:48:55.242(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/packages/fullflavedave_autoflow.js:125:3
W20150930-20:48:55.242(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/boot.js:242:10
W20150930-20:48:55.242(8)? (STDERR)     at Array.forEach (native)
W20150930-20:48:55.242(8)? (STDERR)     at Function._.each._.forEach (/Users/dycbaba/.meteor/packages/meteor-tool/.1.1.9.oddn07++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150930-20:48:55.242(8)? (STDERR)     at /Users/dycbaba/Downloads/meteor-autoflow-demo-master/.meteor/local/build/programs/server/boot.js:137:5

it is not validated under meteor 1.2 ？

thanks and best regards
Eric

**Comment by fullflavedave** [comment]
I hope to take a look at this at the beginning of next week.
